# Generated by Django 5.1 on 2025-06-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jala_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='skills',
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.CharField(choices=[('AWS', 'AWS'), ('QA-Automation', 'QA-Automation'), ('DevOps', 'DevOps'), ('Full Stack Developer', 'Full Stack Developer'), ('Middleware', 'Middleware'), ('WebServices', 'WebServices')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
